version: '3.3'

services:
  db:
    image: mysql
    container_name: mysql
    volumes:
      - $WORDPRESS_PATH/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $DB_PASSWORD 

  wordpress:
    depends_on:
      - db
    image: dockerproxy.cn/wordpress:latest
    container_name: wordpress
    volumes:
      - $WORDPRESS_PATH/wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 80:80
      - 433:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE

  backup-wp:
    depends_on:
     - db
     - wordpress
    image: dockerpull.com/aveltens/wordpress-backup
    container_name: backup-wp
    volumes:
      - $WORDPRESS_PATH/backups-wp:/backups
      - $WORDPRESS_PATH/wordpress_data:/var/www/html
    restart: always
    environment:
      MYSQL_ENV_MYSQL_USER: $MYSQL_USER 
      MYSQL_ENV_MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ENV_MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_PORT_3306_TCP_PORT: $MYSQL_PORT


